FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements/core.txt docker/requirements/
COPY docker/requirements/support-services.txt docker/requirements/
RUN pip install --no-cache-dir -r docker/requirements/support-services.txt
RUN python -m nltk.downloader stopwords punkt

COPY common/ common/
COPY generator_service/ generator_service/
COPY notification_service/ notification_service/
COPY reminder_service/ reminder_service/
COPY insight_service/ insight_service/
COPY docker/entrypoints/ docker/entrypoints/

EXPOSE 5003

ENV GATEWAY_URL=http://localhost:5003

CMD ["python", "docker/entrypoints/run_support_services.py"]
